### ISSUE TITLE
Handle NA in decorrelate

### ISSUE THREAD

**Issue by koalive** [menchelab/BioProfiling.jl#9]
The `decorrelate` function does not handle missing values properly (it seems all columns are counted as correlated to the first column being filled with missing values).

**Comment by bednarsky** [comment]
Same issue if there are `inf` in the data frame.

**Comment by koalive** [comment]
The way to handle these cases seem to depend a lot on why there are such values in the data. 9101e0c9d7fcad62365bb65cc212198f06852af5 adds some tests that will throw a more explicit AssertionError when this is the case, so that the user can decide what to do (e.g. using a `MissingFilter` to remove entries with missing values).
I'm closing this issue for now but this could be re-opened if there a solution that would work in most cases and wouldn't mislead users in ignoring prior issues with their data.
